version: "3.8"
services:
   app:
     build: .
     volumes:
       - .:/app
     working_dir: /app
     command: cargo watch -x run
     depends_on:
       - db
   db:
     image: mysql:8.0
     platform: linux/x86_64
     environment:
       MYSQL_DATABASE: practice
       MYSQL_ROOT_PASSWORD: "password"
       TZ: Asia/Tokyo
     ports:
       - 3331:3306
     volumes:
       - ./db_data:/var/lib/mysql
